[package]
name = "TrelloBatchRunner"
version = "0.1.0"
authors = ["Corrina Sivak <csivak345@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.0"
tokio = "1.2.0"
serde = "1.0.123"